---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: wordpress-pvc
   labels:
      name: wordpress-pvc
spec:
   accessModes:
   - ReadWriteOnce
   storageClassName: do-block-storage 
   resources:
      requests:
         storage: 1Gi