---
apiVersion: v1
kind: Pod
metadata:
  name: dov-pod
  labels:
    name: dov-pod
    app: dov
    tier: backend
  annotations:
    cost-center: abc123
spec:
  containers:
    - name: dov-contatiner # name
      image: stackupiss/dov-bear:v2 # image
      imagePullPolicy: IfNotPresent
      ports: 
      - containerPort: 3000
      env: 
      - name: INSTANCE_NAME
        value: dov-bear
      - name: INSTANCE_HASH
        valueFrom:
          fieldRef:
           fieldPath: metadata.annotations['cost-center']
