---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  labels:
    name: dov-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: dov-pod
      version: v1
  template:  #To specify pods
    metadata:
      name: dov-pod
      labels:
        name: dov-pod
        version: v1
    spec:
      containers:
      - name: dov-container
        image: stackupiss/dov-bear:v2
        imagePullPolicy: IfNotPresent
        env:
        - name: INSTANCE_NAME
          value: dov
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 3000
      

