---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  labels:
    name: dov-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: dov-pod
      version: v1
  template:  #To specify pods
    metadata:
      name: dov-pod
      labels:
        name: dov-pod
        version: v1
    spec:
      containers:
      - name: dov-container
        image: stackupiss/dov-bear:v2
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: dov-secret
        ports:
        - name: dov-port
          containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  labels:
    name: dov-svc
spec:
  type: ClusterIP
  selector:
    name: dov-pod
    version: v1
  ports:
  - port: 8080
    targetPort: dov-port

