---
# db service
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  labels:
    name: bggdb-svc 
spec:
  type: ClusterIP
  selector:
    name: bggapp-pod
  ports:
  - port: 3306
    targetPort: bgg-port
